# Generated by Django 5.1.6 on 2025-12-03 19:30

import apps_base._base.model_fields
import datetime
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_remove_categorytranslation_strong_suits_and_more'),
        ('product_price', '0002_productprice_max_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='max_duration',
            field=apps_base._base.model_fields.DurationField(default=datetime.timedelta(days=100), verbose_name='Max duration'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_group',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_price.pricegroup', verbose_name='Price Group'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.RunSQL(
            sql = """
            INSERT INTO product_price_pricegroup (id, store_id, description, created_time, modified_time, is_default )
            SELECT id, (select id from entity_store LIMIT 1), description, NOW(), NOW(), true FROM product_prices_pricegroup;

            INSERT INTO product_price_productprice (id, price_group_id, price, pricing_type, min_order_quantity, max_order_quantity, min_duration, max_duration, valid_from, valid_to, created_time, modified_time, sequence )
            SELECT id, price_group_id,price,  pricing_type, min_order_quantity, max_order_quantity, min_duration, max_duration, valid_from, valid_to, created_time, modified_time, 100 FROM product_prices_pricegroupprice;

            """,
            reverse_sql = """
            """
        )
    ]

