# Generated by Django 5.1.7 on 2025-12-01 10:42

import apps_base._base.managers
import apps_base._base.model_fields
import apps_base._base.models
import apps_shared.product_price.manager
import apps_shared.product_price.models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0011_store_website_old_website_alter_store_website'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscountGroup',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('group_number', apps_base._base.model_fields.CharField(max_length=100, unique=True, verbose_name='Group number')),
                ('description', apps_base._base.model_fields.CharField(max_length=100, verbose_name='Discount reference')),
                ('is_default', apps_base._base.model_fields.BooleanField(default=False, verbose_name='Default price group')),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('store', apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
            },
            bases=(apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_base._base.managers.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('email', apps_base._base.model_fields.CharField(blank=True, max_length=100, null=True)),
                ('discount_code', apps_base._base.model_fields.CharField(max_length=30, unique=True)),
                ('discount_abs', apps_base._base.model_fields.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('discount_perc', apps_base._base.model_fields.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('minimal_order_amount', apps_base._base.model_fields.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('valid_from', apps_base._base.model_fields.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', apps_base._base.model_fields.DateTimeField(default=apps_shared.product_price.models.return_date_time_latest)),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount coupon',
                'verbose_name_plural': 'Discount coupons',
            },
            bases=(parler.models.TranslatableModelMixin, apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_shared.product_price.manager.DiscountCouponManager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('description', apps_base._base.model_fields.CharField(max_length=50, unique=True, verbose_name='Price group')),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('store', apps_base._base.model_fields.ForeignKey(default=apps_shared.product_price.models.get_default_store, on_delete=django.db.models.deletion.CASCADE, to='entity.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Price group',
                'verbose_name_plural': 'Price groups',
            },
            bases=(apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_base._base.managers.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscountCoupon',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('discount_coupon', apps_base._base.model_fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_price.discountcoupon', verbose_name='Discount Coupon')),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product', apps_base._base.model_fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product discount coupon',
                'verbose_name_plural': 'Product discount coupons',
            },
            bases=(apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_base._base.managers.BaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='products',
            field=apps_base._base.model_fields.ManyToManyField(blank=True, help_text='Leave empty to make available for all products', through='product_price.ProductDiscountCoupon', to='product.product'),
        ),
        migrations.CreateModel(
            name='ProductDiscountGroup',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('group_number', apps_base._base.model_fields.CharField(max_length=100, unique=True, verbose_name='Group number')),
                ('description', apps_base._base.model_fields.CharField(max_length=100, verbose_name='Discount reference')),
                ('include_children', apps_base._base.model_fields.BooleanField(default=False)),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('store', apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'Discount group',
                'verbose_name_plural': 'Discount groups',
            },
            bases=(parler.models.TranslatableModelMixin, apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_shared.product_price.manager.DiscountGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('price', apps_base._base.model_fields.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price')),
                ('valid_from', apps_base._base.model_fields.DateTimeField(default=django.utils.timezone.now, verbose_name='valid from')),
                ('valid_to', apps_base._base.model_fields.DateTimeField(default=apps_shared.product_price.models.return_date_time_latest, verbose_name='valid to')),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('price_group', apps_base._base.model_fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_price.pricegroup', verbose_name='Price Group')),
                ('product', apps_base._base.model_fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Price group price',
                'verbose_name_plural': 'Price group prices',
            },
            bases=(apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_base._base.managers.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCouponTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('discount_label', apps_base._base.model_fields.CharField(max_length=100, verbose_name='discount label')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product_price.discountcoupon')),
            ],
            options={
                'verbose_name': 'Discount coupon Translation',
                'db_table': 'product_price_discountcoupon_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('discount_perc', apps_base._base.model_fields.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Discount percentage')),
                ('min_order_quantity', apps_base._base.model_fields.IntegerField(default=0, verbose_name='Min quantity order discount')),
                ('max_order_quantity', apps_base._base.model_fields.IntegerField(default=9999999, verbose_name='Max quantity order discount')),
                ('valid_from', apps_base._base.model_fields.DateTimeField(default=django.utils.timezone.now, verbose_name='valid from')),
                ('valid_to', apps_base._base.model_fields.DateTimeField(default=apps_shared.product_price.models.return_date_time_latest, verbose_name='valid to')),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                #('customer', apps_base._base.model_fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('customer_discount_group', apps_base._base.model_fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_price.customerdiscountgroup', verbose_name='Customer discount group')),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product', apps_base._base.model_fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('product_discount_group', apps_base._base.model_fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_price.productdiscountgroup', verbose_name='Product discount group')),
            ],
            options={
                'verbose_name': 'Discount group discount',
                'verbose_name_plural': 'Discount group discounts',
                'indexes': [],
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('product_discount_group__isnull', False), _connector='OR'), name='new_product_or_group')],
            },
            bases=(apps_base._base.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductDiscountGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('discount_label', apps_base._base.model_fields.CharField(default='Not translated', max_length=100, verbose_name='discount label')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product_price.productdiscountgroup')),
            ],
            options={
                'verbose_name': 'Discount group Translation',
                'db_table': 'product_price_productdiscountgroup_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
