# Generated by Django 5.0.6 on 2025-11-28 12:20

import apps_base._base.model_fields
import apps_shared.product_price.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_squashed_0010_alter_entity_created_by_alter_entity_created_time_and_more'),
        ('product_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricegroup',
            name='store',
            field=apps_base._base.model_fields.ForeignKey(default=apps_shared.product_price.models.get_default_store, on_delete=django.db.models.deletion.CASCADE, to='entity.store', verbose_name='Store'),
        ),
    ]
