# Generated by Django 5.1.6 on 2025-12-03 10:06

import apps_base._base.model_fields
import datetime
from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='max_duration',
            field=apps_base._base.model_fields.DurationField(default=datetime.timedelta(days=365), verbose_name='Max duration'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='max_order_quantity',
            field=apps_base._base.model_fields.IntegerField(default=9999999, verbose_name='max quantity order discount'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='min_duration',
            field=apps_base._base.model_fields.DurationField(default=datetime.timedelta(0), verbose_name='Min duration'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='min_order_quantity',
            field=apps_base._base.model_fields.IntegerField(default=0, verbose_name='min quantity order discount'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='pricing_type',
            field=apps_base._base.model_fields.CharField(choices=[('price', 'Price'), ('price_per_hour', 'Price per hour'), ('price_per_day', 'Price per day'), ('percentage_total', 'Percentage total'), ('percentage_line', 'Percentage line')], default='price', max_length=100, verbose_name='Pricing type'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='sequence',
            field=apps_base._base.model_fields.FloatField(default=100, editable=False, verbose_name='Sequence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='customer',
            field=apps_base._base.model_fields.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['product', 'product_discount_group', 'customer_discount_group', 'customer', 'valid_from', 'valid_to'], include=['discount_perc', 'product'], name='product_prices_index'),
        ),
    ]
