# Generated by Django 5.1.7 on 2025-12-08 09:14

import apps_base._base.managers
import apps_base._base.model_fields
import apps_base._base.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        # ('product', '0006_productavailability_and_more'),
        ('product_price', '0002_productprice_max_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdiscountgroup',
            name='is_default',
        ),
        migrations.AddField(
            model_name='discount',
            name='max_duration',
            field=apps_base._base.model_fields.DurationField(default=datetime.timedelta(days=100), verbose_name='Max duration'),
        ),
        migrations.AddField(
            model_name='discount',
            name='min_duration',
            field=apps_base._base.model_fields.DurationField(default=datetime.timedelta(0), verbose_name='Min duration'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='customer',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='customer_discount_group',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_price.customerdiscountgroup', verbose_name='Customer discount group'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='max_duration',
            field=apps_base._base.model_fields.DurationField(default=datetime.timedelta(days=100), verbose_name='Max duration'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_group',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_price.pricegroup', verbose_name='Price Group'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='pricing_type',
            field=apps_base._base.model_fields.CharField(choices=[('price', 'Price per quantity'), ('price_per_hour', 'Price per hour (Reservation product)'), ('price_per_day', 'Price per day (Reservation product)'), ('percentage_total', 'Percentage total'), ('percentage_line', 'Percentage line'), ('percentage_parent', 'Percentage Parent')], default='price', max_length=100, verbose_name='Pricing type'),
        ),

        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='ProductPriceGroup',
            fields=[
                ('id', apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', apps_base._base.model_fields.DateTimeField(auto_now_add=True)),
                ('modified_time', apps_base._base.model_fields.DateTimeField(auto_now=True)),
                ('description', apps_base._base.model_fields.CharField(max_length=50, unique=True, verbose_name='Product price group')),
                ('created_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product price group',
                'verbose_name_plural': 'Product price groups',
            },
            bases=(apps_base._base.models.ModelMixin, models.Model),
            managers=[
                ('objects', apps_base._base.managers.BaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='productprice',
            name='product_price_group',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_price.productpricegroup', verbose_name='Product Price Group'),
        ),
    ]
