# Generated by Django 5.1.6 on 2025-12-24 08:51

import apps_base._base.model_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0003_remove_customerdiscountgroup_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiscountgroup',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='customerdiscountgroup',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='customerdiscountgroup',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerdiscountgroup',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='customerdiscountgroup',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='productdiscountcoupon',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='productdiscountcoupon',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='productdiscountcoupon',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productdiscountcoupon',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='productdiscountcoupon',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='productdiscountgroup',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='productdiscountgroup',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='productdiscountgroup',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productdiscountgroup',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='productdiscountgroup',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='productpricegroup',
            name='created_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='productpricegroup',
            name='created_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='productpricegroup',
            name='id',
            field=apps_base._base.model_fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productpricegroup',
            name='modified_by',
            field=apps_base._base.model_fields.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='productpricegroup',
            name='modified_time',
            field=apps_base._base.model_fields.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
    ]
