# Generated by Django 5.1.6 on 2026-01-12 20:45

import apps_base._base.model_fields
import django.db.models.deletion
from django.db import migrations
import apps_shared.product_price.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productoption_managers_and_more'),
        ('product_price', '0005_alter_customerdiscountgroup_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='pricing_type',
            field=apps_base._base.model_fields.CharField(choices=[('price', 'Price per quantity'), ('price_per_hour', 'Price per hour'), ('price_per_day', 'Price per day'), ('percentage_total', 'Percentage total'), ('percentage_line', 'Percentage line'), ('percentage_parent', 'Percentage Parent')], default='price', max_length=100, verbose_name='Pricing type'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_group',
            field=apps_base._base.model_fields.ForeignKey(default=apps_shared.product_price.models.PriceGroup.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='product_price.pricegroup', verbose_name='Price Group'),
        ),
        migrations.AddField(
            model_name='discount',
            name='option',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_option', to='product.productoption', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='option',
            field=apps_base._base.model_fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_option', to='product.productoption', verbose_name='Option'),
        ),
    ]
