# Generated by Django 5.1.6 on 2026-01-25 18:43

import apps_base._base.model_fields
import datetime
import django.utils.timezone
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_managers_alter_product_type'),
        ('product_price', '0006_productprice_option_for_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='needs_products',
            field=apps_base._base.model_fields.IntegerField(blank=True, help_text='Fill in number of products that for the discount coupon to be valid. Use -quantity to use distinct number of products, leave empty to use all products.', null=True, verbose_name='Quantity needed of allowed products'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount_abs',
            field=apps_base._base.model_fields.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Absolute discount'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount_code',
            field=apps_base._base.model_fields.CharField(max_length=30, unique=True, verbose_name='Discount code'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount_perc',
            field=apps_base._base.model_fields.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='email',
            field=apps_base._base.model_fields.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='minimal_order_amount',
            field=apps_base._base.model_fields.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Minimal order amount'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='products',
            field=apps_base._base.model_fields.ManyToManyField(blank=True, help_text='Leave empty to make available for all products', through='product_price.ProductDiscountCoupon', to='product.product', verbose_name='Allowed for Products'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='valid_from',
            field=apps_base._base.model_fields.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='valid_to',
            field=apps_base._base.model_fields.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0), verbose_name='Valid to'),
        ),
    ]
