# Generated by Django 5.1.7 on 2026-03-02 10:25

import apps_base._base.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0007_discountcoupon_needs_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=apps_base._base.model_fields.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='pricing_type',
            field=apps_base._base.model_fields.CharField(choices=[('price', 'Price per quantity'), ('price_per_hour', 'Price per hour'), ('price_per_day', 'Price per day'), ('percentage_total', 'Percentage of total value'), ('percentage_parent', 'Percentage of parent value')], default='price', max_length=100, verbose_name='Pricing type'),
        ),
    ]
