# Generated by Django 5.1.7 on 2026-03-02 12:46

import apps_base._base.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0008_alter_productprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='pricing_type',
            field=apps_base._base.model_fields.CharField(choices=[('price', 'Price per unit'), ('price_per_hour', 'Price per hour'), ('price_per_day', 'Price per day'), ('percentage', 'Percentage of Value'), ('percentage_total', 'Percentage of total value'), ('percentage_parent', 'Percentage of parent value')], default='price', max_length=100, verbose_name='Pricing type'),
        ),
    ]
