# Generated by Django 5.0.6 on 2025-11-03 12:44

import apps_base._base.model_fields
import django.db.models.deletion
import apps_base.entity.managers
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_alter_entity_created_by_alter_entity_created_time_and_more'),
        ('product_price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_abs',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='pricing_type',
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_perc',
            field=apps_base._base.model_fields.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Discount percentage'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_order_quantity',
            field=apps_base._base.model_fields.IntegerField(default=9999999, verbose_name='Max quantity order discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_order_quantity',
            field=apps_base._base.model_fields.IntegerField(default=0, verbose_name='Min quantity order discount'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='store',
            field=apps_base._base.model_fields.ForeignKey(default=entity.managers.StoreManager.get_current, on_delete=django.db.models.deletion.CASCADE, to='entity.store', verbose_name='Store'),
        ),
    ]
